env:
  es2017: true
  browser: true
  node: true
  commonjs: true

extends:
  - 'htmlacademy/vanilla'

parserOptions:
  ecmaVersion: 2019
  sourceType: module

overrides:
  - files: '*.ts'
    parser: '@typescript-eslint/parser'
    extends:
      - plugin:@typescript-eslint/recommended
